### PR TITLE
Added support for XB200

### PR DESCRIPTION
**Pull request by piranha32**

### CODE REVIEW

**Comment by osqzss** [comment]
Quick question. What is XB200? I firstly thought it's one of the USRP platforms but couldn't find the name.

**Comment by piranha32** [comment]
Transverter board for bladerf expanding frequency range below 300MHz. For frequencies above 300MHz the board has a bypass path, but it needs to be enabled and initialized to work properly. https://www.nuand.com/blog/product/hf-vhf-transverter/

**Comment by osqzss** [comment]
Got it. It's explained in your code. I should've look into the file changes first.

**Comment by osqzss** [comment]
Thank you for your contribution.

**Comment by piranha32** [comment]
Thanks for merge

**Comment by osqzss** [comment]
I replaced all the white spaces with tabs.

**Pull request merged**
